### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by drjwbaker** [quirksahern/Runtime#1]
We need a roadmap for future development options.

**Comment by drjwbaker** [comment]
To include:

- [ ] Optional pathways, which demonstrate different types of compute job, and/or different forms of energy (dis)proportionality.
- [ ] Possible development options (e.g. VR/AR, physical card based).
- [ ] Stronger connection to the literature -- pedagogical connection

**Comment by quirksahern** [comment]
The above topics have been included in roadmap.md
